### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by ghost** [XShar/simple_trashe_gen_module#1]
Привет, чёт не работает. Файлы 12kb получаются постоянно.
Можешь запилить видос?

**Comment by XShar** [comment]
Привет, только сейчас заметил тиккет.
А что неработает.
Там генерация инструкций "на лету", также случайный вызов API, несложная программа.
Нужно собрать на FASM fake_instructions.asm, далее подцепить к пректу, функция do_fake_instr() генерирует инструкции, в случайном порядке.
В проекте, всё подключено, в example.cpp пример работы.
Проверял вроде работало.
Пишите лучше на форум ru-sfera.org, я здесь редко бываю.
